### ISSUE TITLE
Nick list uses default, variable-width fonts

### ISSUE THREAD

**Issue by Xiretza** [glowing-bear/glowing-bear#1033]
Ever since an update that can't have been much more than a week ago, the nicklist uses the default `"Helvetica Neue", Helvetica, Arial, sans-serif` fonts as defined in `scaffolding.less`. Instead, it should use the preferred font, as defined in the settings.

Adding `class="favorite-font"` to the `#nicklist` element accomplishes this.

**Comment by lorenzhs** [comment]
You can modify the design to your liking by customising the CSS (in the "Custom CSS" box in settings). It's called "Hide embedded content by default" and results in embedded content not being *loaded* unless you expand it.

**Comment by lorenzhs** [comment]
Update: it was https://github.com/glowing-bear/glowing-bear/pull/989/files that broke this because it moved the nicklist outside the bufferlines div.

**Comment by lorenzhs** [comment]
Fixed in https://github.com/glowing-bear/glowing-bear/commit/7ecd6c0c16d2b8849b7319aefb61d34c700e7dac -- try https://latest.glowing-bear.org in around 15 minutes

**Comment by Xiretza** [comment]
Unfortunately, it still doesn't seem to work. Since the nicklist only gets added to the DOM when a channel buffer is selected, the fancy angular(?) stuff that applies the style to all `.favorite-font` elements gets run before the element exists. Changing the preferred font in the settings forces an update and thus fixes the nicklist, but only until the next reload.

I think I'll just add my own `.favorite-font` rule to the custom CSS, seems like a more robust solution anyway.

**Comment by lorenzhs** [comment]
Ah shit. We'll have to fix that properly, too, though
